### ISSUE TITLE
HTTPS not enforced

### ISSUE THREAD

**Issue by tf** [pubmob-com/pubmob#17]
The page appears to work with HTTPS, but it is currently not enforced. The Flexbooker iframe uses HTTPS, but Chrome still displays warnings and refuses to auto-fill payment information when the outer page is accessed via HTTP. GitHub pages appears to have an option to enforce HTTPS:

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site 

I suggest to enable that to make the checkout process smoother and look more secure.

**Comment by jlangr** [comment]
Great, thanks for the tip--I set it to enforce HTTPS. Let me know if it looks good from your end.

**Comment by tf** [comment]
Yeah, looks good now :+1:
