### ISSUE TITLE
Mobile layout problem 

### ISSUE THREAD

**Issue by jbrains** [pubmob-com/pubmob#5]
This is my pub overview page on Firefox on Android. I haven't tested extensively. The title is obscured by the menu icon.

![Screenshot_20200807-184729_Firefox](https://user-images.githubusercontent.com/61505/89691159-9dccb780-d8de-11ea-88a8-4bcb7bc82752.jpg)

**Comment by jlangr** [comment]
this one has been there a while... I blame Skylar who coded it :-), but mostly myself for not figuring it out a couple months ago when I took a few minutes look. I will get to it ASAP; it's in the top 3 things to do at this point.

**Comment by jlangr** [comment]
please try again and let me know if it's better. It still is a little wonky to me but at least functional.

**Comment by jbrains** [comment]
It looks good to me. Thank you.

**Comment by jlangr** [comment]
thanks for taking a look!
